name: naqshkaar_designer
description: Professional Urdu Graphic Designer App.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^1.1.2
  gal: ^2.3.3
  file_picker: 10.3.10
  image: ^4.5.4
  path_provider: ^2.1.2
  pdf: ^3.11.0
  printing: ^5.12.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Gulzar
      fonts:
        - asset: assets/fonts/Gulzar-Regular.ttf
    - family: NotoNastaliqUrdu
      fonts:
        - asset: assets/fonts/NotoNastaliqUrdu-Regular.ttf
    - family: MehrNastaliq
      fonts:
        - asset: assets/fonts/MehrNastaliq.ttf
    - family: AlMajeedQuranic
      fonts:
        - asset: assets/fonts/AlMajeedQuranic.ttf
    - family: BombayBlack
      fonts:
        - asset: assets/fonts/BombayBlack.ttf
    - family: AlviNastaleeq
      fonts:
        - asset: assets/fonts/AlviNastaleeq.ttf
    - family: JameelNooriNastaleeq
      fonts:
        - asset: assets/fonts/JameelNooriNastaleeq.ttf
