import 'dart:math' as math;
import 'package:flutter/material.dart';

class PremiumShapeCatalog {
  static const List<String> shapeNames = [
    'Rectangle','Rounded Box','Circle','Ellipse','Triangle','Diamond','Pentagon','Hexagon','Octagon','Star','Star Burst','Heart','Cloud','Sun','Moon','Arrow Right','Arrow Left','Arrow Up','Arrow Down','Chevron Right','Chevron Left','Plus','Minus','Cross','Ring','Pill','Tag','Ticket','Badge','Shield','Shield Round','Crown','Gem','Leaf','Flower','Drop','Lightning','Flame','Ribbon','Bookmark','Flag','Speech Bubble','Thought Bubble','Callout','Bracket','Corner','Wave','Zigzag','Arch','House','Hex Badge','Octa Badge','Gear','Target','Bullseye','Check','X Mark','Play','Pause','Stop','Skip','Download','Upload','Link','Paperclip','Lock','Unlock','Keyhole','Eye','Message','Camera','Music','Location Pin','Globe','Book','Folder','Calendar','Clock','User','Users','Medal','Trophy','Gift','Bell','Sparkle','Magic Wand','Palette','Pencil','Brush','Scissors','Frame','Photo Frame','Certificate','Seal','Rosette','Islamic Star','Islamic Tile','Mosque Dome','Mihrab','Lantern','Tasbeeh','Quran Stand','Calligraphy Frame','Decorative Motif','Floral Motif','Geometric Motif'
  ];
  static const List<String> borderNames = [
    'Classic Thin','Classic Double','Classic Triple','Rounded Line','Rounded Double','Dashed','Dotted','Dash Dot','Bold Frame','Soft Frame','Inner Line','Outer Line','Inset Double','Inset Triple','Corner Brackets','Square Brackets','Round Brackets','Elegant Corners','Floral Corners','Leaf Corners','Star Corners','Diamond Corners','Circle Corners','Islamic Corners','Arabesque','Geometric','Hex Tile','Octagon','Scallop','Wave','Zigzag','Rope','Chain','Beaded','Pearl','Gold Style','Royal','Luxury','Minimal','Modern','Classic Ornament','Victorian','Certificate','Wedding','Invitation','Ramadan','Eid','Quran','Nikkah','Madrasa','School','Announcement','Business','Social Post','Poster','A4 Classic','A4 Modern','A4 Elegant','Square Social','Story Frame','Landscape','Portrait','Photo Frame','Double Inner','Double Outer','Triple Inner','Triple Outer','Shadow Frame','Soft Shadow','Neon Edge','Gradient Edge','Broken Corners','Cut Corners','Rounded Cut','Ticket Edge','Scalloped Edge','Festive','Floral','Rose','Vine','Leaf Vine','Tulip','Lotus','Starburst','Sunburst','Moon Star','Lantern','Mosque','Mihrab','Arabic Geometric','Persian','Ottoman','Moroccan','Andalusian','Kashmir','Modern Islamic','Minimal Islamic','Premium Gold','Premium Silver','Premium Purple','Designer Signature','Royal Seal'
  ];
  static const List<String> specialTextNames = [
    'Bismillah','Alhamdulillah','SubhanAllah','Allahu Akbar','MashaAllah','InshaAllah','JazakAllah','BarakAllah','Astaghfirullah','La ilaha illallah','Muhammad ﷺ','Quran Verse','Hadith','Dua','Salam','Eid Mubarak','Ramadan Kareem','Jumma Mubarak','Shab-e-Barat','Shab-e-Qadr','Eid ul Fitr','Eid ul Adha','Nikah Mubarak','Mubarak Ho','Welcome','Thank You','Congratulations','Best Wishes','Happy Birthday','Happy Anniversary','Wedding Invitation','Nikah Invitation','Walima Invitation','Aqiqah Mubarak','New Baby','New Home','New Shop','Grand Opening','Admission Open','Annual Function','Prize Distribution','Result Day','Welcome Back','School Event','Madrasa Event','Islamic Conference','Jalsa','Ijtima','Dars-e-Quran','Dars-e-Hadith','Seerat-un-Nabi','Milad-un-Nabi','Hifz-e-Quran','Quran Competition','Naat Competition','Islamic Quiz','Knowledge Is Light','Seek Knowledge','Patience','Gratitude','Prayer','Salah','Sadaqah','Zakat','Tawakkul','Sabr','Shukr','Dua Reminder','Ayatul Kursi','Surah Ikhlas','Surah Falaq','Surah Nas','Surah Rahman','Surah Waqiah','Surah Mulk','Rabbana Dua','Morning Dua','Evening Dua','Travel Dua','Knowledge Dua','Parents Dua','Good Character','Truthfulness','Kindness','Brotherhood','Ummah','Peace','Mercy','Hope','Forgiveness','Love of Allah','Love of Prophet ﷺ','Quran & Sunnah','Islamic Values','Faith & Action','Light of Quran','Path of Guidance','Beautiful Reminder','Daily Reminder','Friday Reminder','Ramadan Reminder','Eid Greeting','Custom Calligraphy'
  ];
  static String specialText(int index) {
    final name = specialTextNames[index.clamp(0, specialTextNames.length - 1)];
    const values = ['بِسْمِ اللّٰهِ الرَّحْمٰنِ الرَّحِيْمِ','الْحَمْدُ لِلّٰهِ','سُبْحَانَ اللّٰهِ','اللّٰهُ أَكْبَرُ','مَاشَاءَ اللّٰهُ','إِنْ شَاءَ اللّٰهُ','جَزَاكَ اللّٰهُ','بَارَكَ اللّٰهُ','أَسْتَغْفِرُ اللّٰهَ','لَا إِلٰهَ إِلَّا اللّٰهُ','مُحَمَّدٌ ﷺ'];
    return index < values.length ? values[index] : name;
  }
}

class CatalogShapePainter extends CustomPainter {
  final int type; final Color fill; final Color stroke; final double strokeWidth; final bool border;
  const CatalogShapePainter({required this.type, required this.fill, required this.stroke, required this.strokeWidth, this.border = false});
  @override void paint(Canvas canvas, Size size) {
    final p = Paint()..color = border ? Colors.transparent : fill..style = PaintingStyle.fill;
    final sp = Paint()..color = stroke..style = PaintingStyle.stroke..strokeWidth = strokeWidth;
    final r = Rect.fromLTWH(strokeWidth / 2, strokeWidth / 2, size.width - strokeWidth, size.height - strokeWidth);
    if (border) { _drawBorder(canvas, r, sp, type); return; }
    final c = Offset(size.width / 2, size.height / 2), w = size.width, h = size.height;
    switch (type % 100) {
      case 0: canvas.drawRect(r,p); break; case 1: canvas.drawRRect(RRect.fromRectAndRadius(r,Radius.circular(_min(w,h)*.16)),p); break;
      case 2: canvas.drawCircle(c,_min(w,h)*.46,p); break; case 3: canvas.drawOval(r,p); break;
      case 4: _poly(canvas,c,_min(w,h)*.48,3,-math.pi/2,p); break; case 5: _poly(canvas,c,_min(w,h)*.48,4,math.pi/4,p); break;
      case 6: _poly(canvas,c,_min(w,h)*.48,5,-math.pi/2,p); break; case 7: _poly(canvas,c,_min(w,h)*.48,6,-math.pi/2,p); break;
      case 8: _poly(canvas,c,_min(w,h)*.48,8,math.pi/8,p); break; case 9: _star(canvas,c,_min(w,h)*.48,5,p); break; case 10: _star(canvas,c,_min(w,h)*.48,12,p); break;
      case 11: _heart(canvas,c,_min(w,h)*.42,p); break; case 12: _cloud(canvas,w,h,p); break; case 13: _sun(canvas,c,_min(w,h)*.28,p); break; case 14: _moon(canvas,c,_min(w,h)*.43,p); break;
      case 15: _arrow(canvas,r,1,0,p); break; case 16: _arrow(canvas,r,-1,0,p); break; case 17: _arrow(canvas,r,0,-1,p); break; case 18: _arrow(canvas,r,0,1,p); break;
      case 19: _chevron(canvas,r,1,p); break; case 20: _chevron(canvas,r,-1,p); break;
      case 21: canvas.drawRect(Rect.fromLTWH(w*.44,h*.15,w*.12,h*.70),p); canvas.drawRect(Rect.fromLTWH(w*.15,h*.44,w*.70,h*.12),p); break;
      case 22: canvas.drawRRect(RRect.fromRectAndRadius(Rect.fromLTWH(w*.15,h*.40,w*.70,h*.20),Radius.circular(h*.1)),p); break;
      case 23: canvas.drawRect(Rect.fromLTWH(w*.15,h*.44,w*.70,h*.12),p); canvas.drawRect(Rect.fromLTWH(w*.44,h*.15,w*.12,h*.70),p); break;
      case 24: canvas.drawCircle(c,_min(w,h)*.35,sp); canvas.drawCircle(c,_min(w,h)*.18,p); break; case 25: canvas.drawRRect(RRect.fromRectAndRadius(r,Radius.circular(_min(w,h)*.48)),p);
      case 26: _tag(canvas,r,p); break; case 27: _ticket(canvas,r,p); break; case 28: _badge(canvas,r,p,6); break; case 29: _badge(canvas,r,p,8); break;
      case 30: _shield(canvas,r,p); break; case 31: _shieldRound(canvas,r,p); break; case 32: _crown(canvas,r,p); break; case 33: _gem(canvas,r,p); break; case 34: _leaf(canvas,r,p); break;
      case 35: _flower(canvas,c,5,_min(w,h)*.22,p); break; case 36: _drop(canvas,c,_min(w,h)*.42,p); break; case 37: _lightning(canvas,r,p); break; case 38: _flame(canvas,r,p); break;
      case 39: _ribbon(canvas,r,p); break; case 40: _bookmark(canvas,r,p); break; case 41: _flag(canvas,r,p); break; case 42: _speech(canvas,r,p); break; case 43: _thought(canvas,r,p); break;
      case 44: _callout(canvas,r,p); break; case 45: _bracket(canvas,r,p); break; case 46: _corner(canvas,r,p); break; case 47: _wave(canvas,r,p); break; case 48: _zigzag(canvas,r,p); break; case 49: _arch(canvas,r,p); break; case 50: _house(canvas,r,p); break;
      default: _poly(canvas,c,_min(w,h)*.46,3+(type%7),(type%2==0?-math.pi/2:math.pi/4),p);
    }
  }
  void _drawBorder(Canvas c,Rect r,Paint p,int t){final inset=(t%5+1)*4.0;final rounded=t%3==0;final layers=1+t%3;for(var i=0;i<layers;i++){final q=r.deflate(i*inset);if(t%7==0)_dashed(c,q,p,10,6);else if(t%7==1)_dotted(c,q,p,5);else if(rounded)c.drawRRect(RRect.fromRectAndRadius(q,Radius.circular(18+t%20.0)),p);else c.drawRect(q,p);}if(t%11==0)for(final o in [Offset(r.left,r.top),Offset(r.right,r.top),Offset(r.left,r.bottom),Offset(r.right,r.bottom)])c.drawCircle(o,10,p);}
  void _dashed(Canvas c,Rect r,Paint p,double dash,double gap){final path=Path()..addRect(r);for(final m in path.computeMetrics()){double d=0;while(d<m.length){final end=_min(d+dash,m.length);c.drawPath(m.extractPath(d,end),p);d+=dash+gap;}}}
  void _dotted(Canvas c,Rect r,Paint p,double gap){for(var x=r.left;x<=r.right;x+=gap*2){c.drawCircle(Offset(x,r.top),p.strokeWidth*.7,p);c.drawCircle(Offset(x,r.bottom),p.strokeWidth*.7,p);}for(var y=r.top;y<=r.bottom;y+=gap*2){c.drawCircle(Offset(r.left,y),p.strokeWidth*.7,p);c.drawCircle(Offset(r.right,y),p.strokeWidth*.7,p);}}
  void _poly(Canvas c,Offset o,double rad,int n,double start,Paint p){final path=Path();for(var i=0;i<n;i++){final a=start+2*math.pi*i/n;final q=o+Offset(math.cos(a)*rad,math.sin(a)*rad);if(i==0)path.moveTo(q.dx,q.dy);else path.lineTo(q.dx,q.dy);}path.close();c.drawPath(path,p);}
  void _star(Canvas c,Offset o,double rad,int n,Paint p){final path=Path();for(var i=0;i<n*2;i++){final a=-math.pi/2+math.pi*i/n;final rr=i.isEven?rad:rad*.45;final q=o+Offset(math.cos(a)*rr,math.sin(a)*rr);if(i==0)path.moveTo(q.dx,q.dy);else path.lineTo(q.dx,q.dy);}path.close();c.drawPath(path,p);}
  void _heart(Canvas c,Offset o,double s,Paint p){final path=Path()..moveTo(o.dx,o.dy+s*.9)..cubicTo(o.dx-s*1.1,o.dy+s*.2,o.dx-s*.7,o.dy-s*.75,o.dx,o.dy-s*.25)..cubicTo(o.dx+s*.7,o.dy-s*.75,o.dx+s*1.1,o.dy+s*.2,o.dx,o.dy+s*.9)..close();c.drawPath(path,p);}
  void _cloud(Canvas c,double w,double h,Paint p){final path=Path()..moveTo(w*.2,h*.62)..cubicTo(w*.12,h*.42,w*.28,h*.24,w*.44,h*.38)..cubicTo(w*.5,h*.15,w*.82,h*.18,w*.82,h*.45)..cubicTo(w*.98,h*.46,w*.94,h*.72,w*.76,h*.72)..lineTo(w*.24,h*.72)..close();c.drawPath(path,p);}
  void _sun(Canvas c,Offset o,double r,Paint p){c.drawCircle(o,r,p);for(var i=0;i<12;i++){final a=i*math.pi/6;c.drawLine(o+Offset(math.cos(a)*r*1.2,math.sin(a)*r*1.2),o+Offset(math.cos(a)*r*1.55,math.sin(a)*r*1.55),p);}}
  void _moon(Canvas c,Offset o,double r,Paint p){final a=Path()..addOval(Rect.fromCircle(center:o.translate(r*.18,-r*.08),radius:r));final b=Path()..addOval(Rect.fromCircle(center:o.translate(r*.45,-r*.18),radius:r));c.drawPath(Path.combine(PathOperation.difference,a,b),p);}
  void _arrow(Canvas c,Rect r,double dx,double dy,Paint p){final path=Path();if(dx!=0){final x=dx>0?r.right:r.left,y=r.center.dy;path.moveTo(dx>0?r.left:r.right,y-r.height*.16);path.lineTo(x-dx*r.width*.18,y-r.height*.16);path.lineTo(x-dx*r.width*.18,y-r.height*.38);path.lineTo(x,y);path.lineTo(x-dx*r.width*.18,y+r.height*.38);path.lineTo(x-dx*r.width*.18,y+r.height*.16);path.lineTo(dx>0?r.left:r.right,y+r.height*.16);}else{final y=dy>0?r.bottom:r.top,x=r.center.dx;path.moveTo(x-r.width*.16,dy>0?r.top:r.bottom);path.lineTo(x-r.width*.16,y-dy*r.height*.18);path.lineTo(x-r.width*.38,y-dy*r.height*.18);path.lineTo(x,y);path.lineTo(x+r.width*.38,y-dy*r.height*.18);path.lineTo(x+r.width*.16,y-dy*r.height*.18);path.lineTo(x+r.width*.16,dy>0?r.top:r.bottom);}path.close();c.drawPath(path,p);}
  void _chevron(Canvas c,Rect r,double dir,Paint p){final x=dir>0?r.left:r.right,mid=r.center.dy,end=dir>0?r.right:r.left;final path=Path()..moveTo(x,r.top)..lineTo(end,mid)..lineTo(x,r.bottom)..lineTo(dir>0?x+r.width*.22:x-r.width*.22,mid)..lineTo(end-dir*r.width*.22,r.top)..close();c.drawPath(path,p);}
  void _tag(Canvas c,Rect r,Paint p){final path=Path()..moveTo(r.left+r.width*.18,r.top)..lineTo(r.right-r.width*.18,r.top)..lineTo(r.right,r.center.dy)..lineTo(r.right-r.width*.18,r.bottom)..lineTo(r.left+r.width*.18,r.bottom)..lineTo(r.left,r.center.dy)..close();c.drawPath(path,p);}
  void _ticket(Canvas c,Rect r,Paint p){c.drawRRect(RRect.fromRectAndRadius(r,Radius.circular(12)),p);} void _badge(Canvas c,Rect r,Paint p,int n)=>_poly(c,r.center,_min(r.width,r.height)*.46,n,-math.pi/2,p);
  void _shield(Canvas c,Rect r,Paint p){final path=Path()..moveTo(r.center.dx,r.top)..lineTo(r.right,r.top+r.height*.2)..lineTo(r.right-r.width*.08,r.center.dy+r.height*.2)..quadraticBezierTo(r.center.dx,r.bottom,r.left+r.width*.08,r.center.dy+r.height*.2)..lineTo(r.left,r.top+r.height*.2)..close();c.drawPath(path,p);} void _shieldRound(Canvas c,Rect r,Paint p)=>c.drawRRect(RRect.fromRectAndRadius(r.deflate(r.width*.08),Radius.circular(30)),p);
  void _crown(Canvas c,Rect r,Paint p){final path=Path()..moveTo(r.left,r.bottom)..lineTo(r.left+r.width*.12,r.top)..lineTo(r.center.dx-r.width*.08,r.bottom-r.height*.35)..lineTo(r.center.dx,r.top)..lineTo(r.center.dx+r.width*.08,r.bottom-r.height*.35)..lineTo(r.right-r.width*.12,r.top)..lineTo(r.right,r.bottom)..close();c.drawPath(path,p);} void _gem(Canvas c,Rect r,Paint p)=>_poly(c,r.center,_min(r.width,r.height)*.46,6,0,p);
  void _leaf(Canvas c,Rect r,Paint p){final path=Path()..moveTo(r.center.dx,r.top)..quadraticBezierTo(r.right,r.center.dy,r.center.dx,r.bottom)..quadraticBezierTo(r.left,r.center.dy,r.center.dx,r.top)..close();c.drawPath(path,p);} void _flower(Canvas c,Offset o,int n,double r,Paint p){for(var i=0;i<n;i++){final a=i*2*math.pi/n;c.drawCircle(o+Offset(math.cos(a)*r*.8,math.sin(a)*r*.8),r*.55,p);}c.drawCircle(o,r*.35,p);} void _drop(Canvas c,Offset o,double r,Paint p){final path=Path()..moveTo(o.dx,o.dy-r)..quadraticBezierTo(o.dx+r,o.dy,o.dx,o.dy+r)..quadraticBezierTo(o.dx-r,o.dy,o.dx,o.dy-r)..close();c.drawPath(path,p);}
  void _lightning(Canvas c,Rect r,Paint p){final path=Path()..moveTo(r.left+r.width*.55,r.top)..lineTo(r.left+r.width*.2,r.center.dy)..lineTo(r.left+r.width*.48,r.center.dy)..lineTo(r.left+r.width*.35,r.bottom)..lineTo(r.right-r.width*.2,r.top+r.height*.4)..lineTo(r.left+r.width*.55,r.top+r.height*.4)..close();c.drawPath(path,p);} void _flame(Canvas c,Rect r,Paint p){final path=Path()..moveTo(r.center.dx,r.bottom)..cubicTo(r.left,r.bottom-r.height*.3,r.left+r.width*.2,r.top+r.height*.1,r.center.dx,r.top)..cubicTo(r.right-r.width*.1,r.top+r.height*.3,r.right,r.bottom-r.height*.25,r.center.dx,r.bottom)..close();c.drawPath(path,p);}
  void _ribbon(Canvas c,Rect r,Paint p)=>c.drawRRect(RRect.fromRectAndRadius(r.deflate(r.width*.1),Radius.circular(8)),p); void _bookmark(Canvas c,Rect r,Paint p)=>c.drawRect(r.deflate(r.width*.18),p); void _flag(Canvas c,Rect r,Paint p){c.drawRect(Rect.fromLTWH(r.left+r.width*.18,r.top,r.width*.12,r.height),p);final path=Path()..moveTo(r.left+r.width*.3,r.top+r.height*.12)..lineTo(r.right,r.top+r.height*.3)..lineTo(r.left+r.width*.3,r.top+r.height*.55)..close();c.drawPath(path,p);}
  void _speech(Canvas c,Rect r,Paint p)=>c.drawRRect(RRect.fromRectAndRadius(r.deflate(r.width*.08),Radius.circular(18)),p); void _thought(Canvas c,Rect r,Paint p)=>c.drawOval(r.deflate(r.width*.08),p); void _callout(Canvas c,Rect r,Paint p)=>c.drawRRect(RRect.fromRectAndRadius(r.deflate(r.width*.08),Radius.circular(10)),p);
  void _bracket(Canvas c,Rect r,Paint p){final path=Path()..moveTo(r.left+r.width*.28,r.top)..lineTo(r.left,r.top)..lineTo(r.left,r.bottom)..lineTo(r.left+r.width*.28,r.bottom)..moveTo(r.right-r.width*.28,r.top)..lineTo(r.right,r.top)..lineTo(r.right,r.bottom)..lineTo(r.right-r.width*.28,r.bottom);c.drawPath(path,p);} void _corner(Canvas c,Rect r,Paint p){c.drawLine(Offset(r.left,r.top),Offset(r.left+r.width*.3,r.top),p);c.drawLine(Offset(r.left,r.top),Offset(r.left,r.top+r.height*.3),p);c.drawLine(Offset(r.right,r.bottom),Offset(r.right-r.width*.3,r.bottom),p);c.drawLine(Offset(r.right,r.bottom),Offset(r.right,r.bottom-r.height*.3),p);}
  void _wave(Canvas c,Rect r,Paint p){final path=Path()..moveTo(r.left,r.center.dy);for(var i=0;i<4;i++){final x=r.left+r.width*i/4;path.cubicTo(x+r.width/12,r.top,x+r.width/6,r.bottom,x+r.width/4,r.center.dy);}c.drawPath(path,p);} void _zigzag(Canvas c,Rect r,Paint p){final path=Path()..moveTo(r.left,r.center.dy);for(var i=1;i<=8;i++)path.lineTo(r.left+r.width*i/8,r.top+(i.isEven?r.height*.75:r.height*.25));c.drawPath(path,p);} void _arch(Canvas c,Rect r,Paint p)=>c.drawArc(Rect.fromLTWH(r.left,r.top,r.width,r.height*1.6),math.pi,math.pi,false,p); void _house(Canvas c,Rect r,Paint p){final path=Path()..moveTo(r.left,r.center.dy)..lineTo(r.center.dx,r.top)..lineTo(r.right,r.center.dy)..lineTo(r.right,r.bottom)..lineTo(r.left,r.bottom)..close();c.drawPath(path,p);}
  double _min(double a,double b)=>a<b?a:b;
  @override bool shouldRepaint(covariant CatalogShapePainter old)=>old.type!=type||old.fill!=fill||old.stroke!=stroke||old.strokeWidth!=strokeWidth||old.border!=border;
}
