from pathlib import Path
import re

# Every feature generator runs before this pass. Normalize the final generated
# controller itself so later generators cannot re-introduce lint-only failures.
path = Path('lib/state/workspace_controller.dart')
text = path.read_text(encoding='utf-8')

# Whole-line guards.
line_guard = re.compile(r'^(?P<indent>\s*)if\s*\((?P<condition>.*)\)\s*(?P<statement>return|continue|break)\s*;\s*$', re.MULTILINE)

def expand_guard(match):
    indent = match.group('indent')
    return f"{indent}if ({match.group('condition').strip()}) {{\n{indent}  {match.group('statement')};\n{indent}}}"

# Inline element-field assignments are generated by several controller
# upgrades (notably Image Studio). Expand them as well; the analyzer reports
# each inline statement even when two guards share one source line.
inline_assignment = re.compile(r'if\s*\((?P<condition>[^()\n]+)\)\s*(?P<statement>[A-Za-z_][A-Za-z0-9_]*\.[A-Za-z_][A-Za-z0-9_]*\s*=\s*[^;\n]+;)')

def expand_assignment(match):
    indent = ''
    return f"if ({match.group('condition').strip()}) {{\n  {match.group('statement').strip()}\n}}"

previous = None
while previous != text:
    previous = text
    text = line_guard.sub(expand_guard, text)
    text = inline_assignment.sub(expand_assignment, text)

# Final verification for both forms. Any match here means this hardening pass
# did not cover a newly generated single-statement if, so fail before Flutter
# analyze rather than spending time on an avoidable red build.
remaining_lines = list(line_guard.finditer(text))
remaining_inline = list(inline_assignment.finditer(text))
if remaining_lines or remaining_inline:
    locations = []
    for match in (remaining_lines + remaining_inline)[:12]:
        locations.append(str(text.count('\n', 0, match.start()) + 1))
    raise SystemExit('Final Dart lint hardening verification failed at line(s): ' + ', '.join(locations))

path.write_text(text, encoding='utf-8')
print('Final Dart lint hardening passed: no targeted single-statement if guards remain.')
